export const USER_LOGIN_FETCH = 'USER_LOGIN_FETCH'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_REGISTER_FETCH = 'USER_REGISTER_FETCH'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

export const USER_LIST_FETCH = 'USER_LIST_FETCH'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE'

export const USER_ADD_FETCH = 'USER_ADD_FETCH'
export const USER_ADD_SUCCESS = 'USER_ADD_FETCH_SUCCESS'
export const USER_ADD_FAILURE = 'USER_ADD_FAILURE'


export const USER_MODIFY_FETCH = 'USER_MODIFY_FETCH'
export const USER_MODIFY_SUCCESS = 'USER_MODIFY_SUCCESS'
export const USER_MODIFY_FAILURE = 'USER_MODIFY_FAILURE'

export const USER_DELETE = 'USER_DELETE'
